### ISSUE TITLE
It doesn't work with `rootDirs`

### ISSUE THREAD

**Issue by evelyne24** [NiGhTTraX/lerna-ts#1]
Thanks for the tutorial! I had to make a change to the `project-references` branch and instead of `rootDir` use `rootDirs`. However, this completely breaks it. Any idea how to use include multiple roots in `foo`?

**Comment by NiGhTTraX** [comment]
Hi @evelyne24, could you please provide a reproducible example?

**Comment by evelyne24** [comment]
You can try it on your example, if you change from `rootDir` to `rootDirs`

**Comment by NiGhTTraX** [comment]
> if you change from rootDir to rootDirs

- `rootDir` controls the output structure of the build folder
- `rootDirs` allows relative imports from multiple folders that will be placed next to each other as part of the build

You shouldn't use one over the other. If you need the functionality provided by `rootDirs` you can just enable it alongside `rootDir`.

**Comment by evelyne24** [comment]
> > if you change from rootDir to rootDirs
> 
> * `rootDir` controls the output structure of the build folder
> * `rootDirs` allows relative imports from multiple folders that will be placed next to each other as part of the build
> 
> You shouldn't use one over the other. If you need the functionality provided by `rootDirs` you can just enable it alongside `rootDir`.

Ok, that makes sense, thanks!

**Comment by NiGhTTraX** [comment]
No problem! I tested locally and `rootDirs` works alongside `rootDir`. I tried using just the former and what happened is that the build output changed structure (it produced `build/src/foo` instead of `build/foo`) and then the other package couldn't find its dependency anymore.

I'm going to close this, but if you have any more questions feel free to reopen it!
