### ISSUE TITLE
Get error on windows  - 'rm' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by zamirdan** [NiGhTTraX/lerna-ts#7]
First of all I think this can be very helpful for someone how just want to start working with Lerna and TS, thank you for this project.

I kind of missing some full instruction to make it work... maybe I missed it...

anyway - whenever I run Lerna run build - I get this error "'rm' is not recognized as an internal or external command,"
What can i do?

**Comment by NiGhTTraX** [comment]
Hey @zamirdan, `rm` was used as part of the [`clean` scripts](https://github.com/NiGhTTraX/lerna-ts/blob/c29d04d30691d485d06d5afbb4ce6517f2483ef2/packages/bar/package.json#L11) which run before building the packages. Since you're using Windows where `rm` is unavailable the script was throwing. I replaced the command with the `rimraf` package so if you pull in the latest master it should work now. Thanks for opening the issue!
